# Generated by Django 5.1.7 on 2025-03-27 08:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_title', models.CharField(help_text='The title of the event', max_length=255)),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('description', wagtail.fields.RichTextField(help_text='A detailed description of the event')),
                ('main_image', models.ForeignKey(blank=True, help_text='Upload the main event image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
