# Generated by Django 5.1.7 on 2025-03-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_remove_eventpage_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetailspage',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='eventdetailspage',
            old_name='main_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='eventdetailspage',
            name='event_title',
        ),
    ]
