# Generated by Django 5.1.7 on 2025-03-30 06:53

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_homepage_eventdetailspage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=wagtail.fields.StreamField([('testimonial', 2)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('text', 0), ('image', 1)]], {})}),
        ),
    ]
