# Generated by Django 5.1.7 on 2025-03-30 07:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_homepage_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='team_members',
            field=wagtail.fields.StreamField([('member', 3)], blank=True, block_lookup={0: ('wagtail.blocks.TextBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('image', 2)]], {})}),
        ),
    ]
